[tool.poetry]
name = "langchain-basics-and-snippets"
version = "0.1.0"
description = ""
authors = ["saifullah <saifu0905@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
dotenv = "^0.9.9"
langchain-openai = "^1.1.11"
langchain-ollama = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
